---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

ci:
  autofix_commit_msg: |
    Chore: pre-commit autofixes

    Signed-off-by: pre-commit-ci[bot] <pre-commit-ci@users.noreply.github.com>
  autoupdate_commit_msg: |
    Chore: pre-commit autoupdate

    Signed-off-by: pre-commit-ci[bot] <pre-commit-ci@users.noreply.github.com>

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
        args:
          - --branch=main
          - --branch=master

  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98 # frozen: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/adrienverge/yamllint.git
    rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7  # frozen: v1.37.1
    hooks:
      - id: yamllint
        types: [yaml]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95  # frozen: v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 192ad822316c3a22fb3d3cc8aa6eafa0b8488360  # frozen: v0.45.0
    hooks:
      - id: markdownlint
        args: ["--fix"]

  - repo: https://github.com/fsfe/reuse-tool
    rev: 9245cd26448e246cda84f70711cc9d5f970855d6  # frozen: v6.1.2
    hooks:
      - id: reuse

  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: 2773c7d04be5d0ceb075f215b6d0a4eacd4a432b  # frozen: v1.7.8.24
    hooks:
      - id: actionlint

  - repo: https://github.com/codespell-project/codespell
    rev: 63c8f8312b7559622c0d82815639671ae42132ac # frozen: v2.4.1
    hooks:
      - id: codespell
        args: ["--ignore-words=.codespell"]

  - repo: https://github.com/python-jsonschema/check-jsonschema.git
    rev: 83b816d020105076daac266dbf6bfed199a2da93  # frozen: 0.34.1
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
      - id: check-jsonschema
        name: Check GitHub Workflows set timeout-minutes
        args:
          - --builtin-schema
          - github-workflows-require-timeout
        files: ^\.github/workflows/[^/]+$
        types:
          - yaml
