---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: Test Python

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths:
      - "tests/**"
      - "pyproject.toml"
      - ".github/workflows/test-python.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "tests/**"
      - "pyproject.toml"
      - ".github/workflows/test-python.yaml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test]"

      - name: Run tests with coverage
        run: |
          pytest --cov --cov-report=term --cov-report=html

      - name: Generate coverage summary
        if: always()
        run: |
          {
            echo "## Test Coverage Report"
            echo "\`\`\`"
            coverage report
            echo "\`\`\`"
          } >> "${GITHUB_STEP_SUMMARY}"

      - name: Upload coverage reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: matrix.python-version == '3.11'
        with:
          name: coverage-reports
          path: htmlcov/
